install:
  - wget http://static.rust-lang.org/dist/rust-0.11.0-x86_64-unknown-linux-gnu.tar.gz
  - tar xzf rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - export PATH=$PATH:$(pwd)/rust-nightly-x86_64-unknown-linux-gnu/bin
  - rustc -v
script:
  - make bench
  - make docs

env:
  global:
    - secure: WqnaJMghhonjDCOadSZ6qmLAckTa4Um26g77JSqF7sRv1I52dmJcDleAyOHP9x4b6v0+4J5xILACMdimYkSfe48vHoVFrIuyfVbnw41+oBFcVIa4fW/MzB9FVe4MSDCIvZZyE2Y0YP2pcPELgdfQyWef+SkbT6G39lHqZ7eWBQ0=
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
